In [1]:
import pandas as pd
import numpy as np

In [2]:
score = [[12, 20, 18], [13, 14, 6], [12, 8, 9], [20, 16, 9]]

In [4]:
df = pd.DataFrame(data=score)
df

0   1   2
0  12  20  18
1  13  14   6
2  12   8   9
3  20  16   9

In [5]:
dars = ['Python', 'C++', 'Java']
name = ['Ali', 'Sara', 'Taha', 'Mahsa']

In [6]:
df = pd.DataFrame(data=score, index=name, columns=dars)
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [7]:
d = {'Python': [12, 13, 12, 20], 'C++': [20, 14, 8, 16], 'Java': [18, 6, 9, 9]}
student = pd.DataFrame(data=d, index=name)
student

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

یک روش درست کردن دیتا فریم با کمک دیکشنری

In [8]:
df.values

array([[12, 20, 18],
       [13, 14,  6],
       [12,  8,  9],
       [20, 16,  9]], dtype=int64)

In [9]:
df.columns

Index(['Python', 'C++', 'Java'], dtype='object')

In [10]:
'Java' in df.columns

True

In [11]:
df.index

Index(['Ali', 'Sara', 'Taha', 'Mahsa'], dtype='object')

In [12]:
df.axes

[Index(['Ali', 'Sara', 'Taha', 'Mahsa'], dtype='object'),
 Index(['Python', 'C++', 'Java'], dtype='object')]

In [14]:
df.dtypes

Python    int64
C++       int64
Java      int64
dtype: object

## Indexing, Selection and Filtering

In [15]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [16]:
df['Python']

Ali      12
Sara     13
Taha     12
Mahsa    20
Name: Python, dtype: int64

In [17]:
df['Python'].values

array([12, 13, 12, 20], dtype=int64)

In [20]:
df[df < 10] = 10
df

Python  C++  Java
Ali        12   20    18
Sara       13   14    10
Taha       12   10    10
Mahsa      20   16    10

In [21]:
df < 11

Python    C++   Java
Ali     False  False  False
Sara    False  False   True
Taha    False   True   True
Mahsa   False  False   True

In [22]:
df[df['C++'] > 11]

Python  C++  Java
Ali        12   20    18
Sara       13   14    10
Mahsa      20   16    10

اینجا طاها رو نیورد چون سی پلاس پلاس رو کم گرفته بود.

---------------
## loc, iloc, iat

In [25]:
df = pd.DataFrame(data=score, index=name, columns=dars)
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [26]:
df.loc['Taha']

Python    12
C++        8
Java       9
Name: Taha, dtype: int64

In [27]:
df.iloc[2]

Python    12
C++        8
Java       9
Name: Taha, dtype: int64

اون آی تو آیلاک به معنی اینتیجر هست و بایستی آرگومان عدد بدیم.
طاها عددش میشه 2


In [29]:
df.iloc[[2]]

Python  C++  Java
Taha      12    8     9

In [30]:
df.loc['Taha', ['Python', 'Java']]

Python    12
Java       9
Name: Taha, dtype: int64

In [31]:
df.iloc[2, [0, 2]]

Python    12
Java       9
Name: Taha, dtype: int64

In [32]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [33]:
df.iloc[:2, [0, 1]]

Python  C++
Ali       12   20
Sara      13   14

In [34]:
df.iloc[0, 1]

20

In [35]:
df.iloc[[0, 1]]

Python  C++  Java
Ali       12   20    18
Sara      13   14     6

In [36]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [40]:
df.iat[0, 1]

20

In [38]:
df.iloc[0]

Python    12
C++       20
Java      18
Name: Ali, dtype: int64

In [39]:
df.iloc[0].iat[1]

20

-------------
## reindex

In [41]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [43]:
df.reindex(['Ali', 'Sara', 'Taha', 'Mahsa', 'Omid'])

Python   C++  Java
Ali      12.0  20.0  18.0
Sara     13.0  14.0   6.0
Taha     12.0   8.0   9.0
Mahsa    20.0  16.0   9.0
Omid      NaN   NaN   NaN

In [44]:
df.reindex(columns=['Python', 'C++', 'Java', 'Pascal'], fill_value=0)

Python  C++  Java  Pascal
Ali        12   20    18       0
Sara       13   14     6       0
Taha       12    8     9       0
Mahsa      20   16     9       0

------------
## sort_values, sort_index

In [45]:
df.sort_values(by='Python')

Python  C++  Java
Ali        12   20    18
Taha       12    8     9
Sara       13   14     6
Mahsa      20   16     9

In [47]:
df.sort_values(by=['Python', 'C++'])

Python  C++  Java
Taha       12    8     9
Ali        12   20    18
Sara       13   14     6
Mahsa      20   16     9

In [48]:
df.sort_index()

Python  C++  Java
Ali        12   20    18
Mahsa      20   16     9
Sara       13   14     6
Taha       12    8     9

------------
## idxmax, sum, mean, describe, transpose

In [3]:
d = {'Python': [12, 13, 12, 20], 'C++': [20, 14, 8, 16], 'Java': [18, 6, 9, 9]}
names = ['Ali', 'Sara', 'Taha', 'Mahsa']
df = pd.DataFrame(data=d, index=names)
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [4]:
df.idxmax()

Python    Mahsa
C++         Ali
Java        Ali
dtype: object

In [5]:
df.sum()

Python    57
C++       58
Java      42
dtype: int64

In [11]:
df.sum(axis='columns')

Ali      50
Sara     33
Taha     29
Mahsa    45
dtype: int64

In [6]:
df.mean()

Python    14.25
C++       14.50
Java      10.50
dtype: float64

In [7]:
df.describe()

Python   C++       Java
count   4.00000   4.0   4.000000
mean   14.25000  14.5  10.500000
std     3.86221   5.0   5.196152
min    12.00000   8.0   6.000000
25%    12.00000  12.5   8.250000
50%    12.50000  15.0   9.000000
75%    14.75000  17.0  11.250000
max    20.00000  20.0  18.000000

In [15]:
df.T

Ali  Sara  Taha  Mahsa
Python   12    13    12     20
C++      20    14     8     16
Java     18     6     9      9

## apply, map, applymap

In [16]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [18]:
m = lambda x: x-1
df.apply(m)

Python  C++  Java
Ali        11   19    17
Sara       12   13     5
Taha       11    7     8
Mahsa      19   15     8

In [21]:
def myfunc(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
df.apply(myfunc)

Python  C++  Java
min      12    8     6
max      20   20    18

وقتی بخواهیم تو یک ستون خاص فانکشن اعمال بشه از مپ استفاده میکنیم.

In [22]:
df['Java'].map(lambda x: x+2)

Ali      20
Sara      8
Taha     11
Mahsa    11
Name: Java, dtype: int64

In [23]:
df

Python  C++  Java
Ali        12   20    18
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

این دیتا فریم اصلی تغییر نکرده ها

In [29]:
df.applymap(lambda x: '%.2f' % x)

Python    C++   Java
Ali    12.00  20.00  18.00
Sara   13.00  14.00   6.00
Taha   12.00   8.00   9.00
Mahsa  20.00  16.00   9.00

این کار رو با مپ نمیشه انجام داد و باید اپلای مپ باشه

In [31]:
df.drop(['Ali'])

Python  C++  Java
Sara       13   14     6
Taha       12    8     9
Mahsa      20   16     9

In [33]:
df.drop(['Java'], axis=1)

Python  C++
Ali        12   20
Sara       13   14
Taha       12    8
Mahsa      20   16

به صورت پیشفرض سطری حذف میکنه، اگر بخواهیم یک ستون حذف بشه باید اون اکسیس رو حتما مشخص کنیم.

## Arithmetic methods with fill values

In [34]:
arr1 = np.arange(12).reshape((4, 3))
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
df1 = pd.DataFrame(data=arr1, columns=list('abc'))
df1

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [36]:
arr2 = np.arange(10).reshape((5, 2))
df2 = pd.DataFrame(data=arr2, columns=list('ab'))
df2

a  b
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [37]:
df2.loc[1, 'b'] = np.nan
df2

a    b
0  0  1.0
1  2  NaN
2  4  5.0
3  6  7.0
4  8  9.0

In [38]:
df1 + df2

a     b   c
0   0.0   2.0 NaN
1   5.0   NaN NaN
2  10.0  12.0 NaN
3  15.0  17.0 NaN
4   NaN   NaN NaN

In [40]:
df1.add(df2, fill_value=0)

a     b     c
0   0.0   2.0   2.0
1   5.0   4.0   5.0
2  10.0  12.0   8.0
3  15.0  17.0  11.0
4   8.0   9.0   NaN

وقتی فیل ولیو صفر باشه اونجاهایی که که یکی از دیتافریم ها عددی ندارن رو صفر میذاره و عمل جمع رو انجام میده.

In [41]:
df1.sub(df2, fill_value=0)

a    b     c
0  0.0  0.0   2.0
1  1.0  4.0   5.0
2  2.0  2.0   8.0
3  3.0  3.0  11.0
4 -8.0 -9.0   NaN

In [42]:
df1

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [43]:
df1.cumsum()

a   b   c
0   0   1   2
1   3   5   7
2   9  12  15
3  18  22  26

## index.name, columns.name

In [47]:
mydict = {'City':['Hamedan', 'Hamedan', 'Hamedan',
                  'Tehran', 'Tehran', 'Tehran'],
            'Year':[1396, 1397, 1398, 1397, 1398, 1399],
            'Pop': [2, 2.2, 3, 8, 8.5, 9]}
f = pd.DataFrame(data=mydict)
f

City  Year  Pop
0  Hamedan  1396  2.0
1  Hamedan  1397  2.2
2  Hamedan  1398  3.0
3   Tehran  1397  8.0
4   Tehran  1398  8.5
5   Tehran  1399  9.0

In [48]:
d = {'Hamedan': {1396: 2, 1397:2.2, 1398:3},
    'Tehran': {1397: 8, 1398: 8.5, 1399: 9}}
frame = pd.DataFrame(data=d)
frame

Hamedan  Tehran
1396      2.0     NaN
1397      2.2     8.0
1398      3.0     8.5
1399      NaN     9.0

به دو نوع مختلف تونستیم دیتا فریم رو پایه ریزی کنیم. دیگه بستگی داره که چه کاری بخواهیم انجام بدیم

In [52]:
frame.index.name = 'year'
frame.columns.name = 'city'
frame

city  Hamedan  Tehran
year                 
1396      2.0     NaN
1397      2.2     8.0
1398      3.0     8.5
1399      NaN     9.0

## Operations between DataFrame & Series

In [54]:
myser = frame.iloc[2]
myser

city
Hamedan    3.0
Tehran     8.5
Name: 1398, dtype: float64

وقتی با آیلوک یک شماره رو میدیم خروجی اش یک سری هست

In [55]:
frame + myser

city  Hamedan  Tehran
year                 
1396      5.0     NaN
1397      5.2    16.5
1398      6.0    17.0
1399      NaN    17.5

## Hierarchical Indexing 

In [56]:
frame = pd.DataFrame({'C++': [6, 7, 4, 16, 14, 13, 15, 7],
                       'Python': [3, 2, 5, 14, 19, 18, 16, 10],
                       'K1': ['one', 'one', 'one', 'two', 'two', 'two', 'two', 'two'],
                       'K2': ['ali', 'reza', 'sara', 'ali', 'reza', 'sara', 'taha', 'farid']})
frame

C++  Python   K1     K2
0    6       3  one    ali
1    7       2  one   reza
2    4       5  one   sara
3   16      14  two    ali
4   14      19  two   reza
5   13      18  two   sara
6   15      16  two   taha
7    7      10  two  farid

نمرات مربوط به دو ترم متوالی است. چند نفر بودن ترم یک افتادن و ترم دو دوباره گرفتن درس رو

In [58]:
df = frame.set_index(['K1', 'K2'])
df

C++  Python
K1  K2                
one ali      6       3
    reza     7       2
    sara     4       5
two ali     16      14
    reza    14      19
    sara    13      18
    taha    15      16
    farid    7      10

ک 1 و ک 2 الان به صورت ایندکس در اومدن و مشخص تر شد

In [59]:
df.sort_index(level=1)

C++  Python
K1  K2                
one ali      6       3
two ali     16      14
    farid    7      10
one reza     7       2
two reza    14      19
one sara     4       5
two sara    13      18
    taha    15      16

روی لول ک2 مرتب سازی انجام شد

In [60]:
df.mean(level='K2')

C:\Users\mrkhe\AppData\Local\Temp/ipykernel_13248/1271298331.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.median(level=1) should use df.groupby(level=1).median().
  df.mean(level='K2')


C++  Python
K2                 
ali    11.0     8.5
reza   10.5    10.5
sara    8.5    11.5
taha   15.0    16.0
farid   7.0    10.0

In [61]:
df

C++  Python
K1  K2                
one ali      6       3
    reza     7       2
    sara     4       5
two ali     16      14
    reza    14      19
    sara    13      18
    taha    15      16
    farid    7      10

In [62]:
df.unstack()

C++                         Python                        
K2    ali farid  reza  sara  taha    ali farid  reza  sara  taha
K1                                                              
one   6.0   NaN   7.0   4.0   NaN    3.0   NaN   2.0   5.0   NaN
two  16.0   7.0  14.0  13.0  15.0   14.0  10.0  19.0  18.0  16.0

ک1 شاخص سطح شماره صفر و ک2 شاخص سطح با شماره یک هست 

In [ ]:
The End